# Generated by Django 5.1.7 on 2025-05-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEmpresaDjango', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='responsable',
        ),
        migrations.AddField(
            model_name='tarea',
            name='empleados',
            field=models.ManyToManyField(blank=True, to='appEmpresaDjango.empleado'),
        ),
    ]
