# Generated by Django 5.1.7 on 2025-05-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEmpresaDjango', '0002_remove_tarea_responsable_tarea_empleados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='empleados',
            field=models.ManyToManyField(blank=True, related_name='tareas', to='appEmpresaDjango.empleado'),
        ),
    ]
