# Generated by Django 5.2.1 on 2025-06-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEmpresaDjango', '0004_tarea_responsables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='responsables',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='responsables',
            field=models.ManyToManyField(blank=True, related_name='proyectos_responsables', to='appEmpresaDjango.empleado'),
        ),
    ]
